In [4]:
import numpy as np

In [5]:
nv = np.zeros(10)
nv

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
v.shape

(40,)

In [11]:
v.dtype

dtype('int64')

In [18]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/version.py'>
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
None


In [16]:
v.shape

(40,)

In [26]:
print(np.ones(16).reshape(4,4))
print(np.full((4,4), True))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [36]:
np.array([] , ndmin = 2)

array([], shape=(1, 0), dtype=float64)

In [37]:
x = np.array([[1,2,3],[4,5,6]])
x , x.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [ ]:
Create a three dimensional array ???

In [40]:
e= np.array([[[1,2],[3,4],[5,6]]])
e , e.shape

(array([[[1, 2],
         [3, 4],
         [5, 6]]]),
 (1, 3, 2))

In [41]:
np.array([],ndmin=3)

array([], shape=(1, 1, 0), dtype=float64)

# Difficulty Level Easy

In [48]:
c = np.arange(8)
print(c)
print(np.flip(c, axis = 0))

[0 1 2 3 4 5 6 7]
[7 6 5 4 3 2 1 0]


In [54]:
x = np.zeros(10)
print(x)
x[5] = 1
x


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [55]:
im = np.array([[[1,0,0], [0,1,0],[0,0,1]]])
im

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])

In [71]:
x= np.zeros(9).reshape(3,3)

x[0:1 , 0:1] =1 
x[1:2 , 1:2]= 1
x[2:3 , 2:3]= 1

print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [83]:
arr = np.array([1, 2, 3, 4, 5], dtype = 'float')
arr

array([1., 2., 3., 4., 5.])

In [85]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr3= arr1*arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [88]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

arr3 = arr1 == arr2

arr3

array([[False, False, False],
       [False, False, False]])

In [97]:
arr=np.arange(10)

arr[arr % 2 ==1]



array([1, 3, 5, 7, 9])

In [99]:
arr=np.arange(10)

arr[arr % 2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [114]:
arr=np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [119]:
arr = np.ones(16).reshape(4,4)
print(arr)
arr[1:3, 1:3] = 0
arr

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [121]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 5]])
print(arr2d)
arr2d[arr2d == 5] = 12
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 5]]
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8 12]]


In [128]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [133]:
arr = np.arange(10).reshape(2,5)
print(arr)
arr[0:1,0:]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4]])

In [141]:
arr= np.arange(10).reshape(2,5)
print(arr[0] , arr[1] )
print(arr[1][1])

[0 1 2 3 4] [5 6 7 8 9]
6


In [145]:
arr= np.arange(16).reshape(4,4)
print(arr)
arr[0:2, 2:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[2],
       [6]])

In [158]:
rand = np.random.randn(10,10)
np.maximum([1,2,3,4,5], [4,6,7,8,9])
print(np.amax(rand))
print(np.amin(rand))


2.680826080137926
-2.517166719996871


In [166]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
z[a==b]
print(z)


[False  True False  True False  True False  True False False]


In [167]:
print(np.intersect1d(a, b))

[2 4]


In [168]:
np.where(a==b)

(array([1, 3, 5, 7]),)

In [177]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

print(names[names == 'Will'])
print(np.where(names == 'Will'))

['Will' 'Will']
(array([2, 4]),)


In [196]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

np.where((names != 'Joe') & (names !='Will'))

(array([0, 3]),)

# Difficulty Level Hard

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [201]:
arr2d = np.arange(1,16).reshape(5,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [202]:
arr4 = np.arange(1,17).reshape(2,2,4)
arr4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [203]:
np.swapaxes(arr2d,0,1)

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

In [223]:
arr10 = np.arange(10)
print(arr10)
x =np.sqrt(arr10)
print(np.where(x<1))
x[x<2] = 0
print(x)


[0 1 2 3 4 5 6 7 8 9]
(array([0]),)
[0.         0.         0.         0.         2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [226]:
arr1 = np.random.randn(12)
arr2= np.random.randn(12)

np.maximum(arr1, arr2)




array([-0.60146512, -1.47844264,  2.07001261,  1.09017387,  0.19927687,
        0.94151197, -0.56842924,  1.16491217,  2.2143172 ,  1.26347142,
        1.05074258,  0.77647543])

In [237]:
names = np.array(['Bob', 'Joe', 'aall', 'Bob', 'Will', 'Joe', 'Joe'])
x = np.unique(names)
print(sorted(x , key=str.lower))


['aall', 'Bob', 'Joe', 'Will']


In [282]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print(np.delete(b, [0,1,2,3,4] , None))


[]


In [281]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])

sampleArray[0:3 , 1:2] = 10

sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [269]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x,y)


array([[ 28.,  64.],
       [ 67., 181.]])

In [272]:
arr5 = np.random.randn(20)
np.cumsum(arr5)

array([-1.43874714, -0.00606431, -1.60671518, -2.60751167, -1.28973317,
       -1.27485846, -1.97660347, -1.92014669, -2.37207804, -1.20396166,
        0.40342794, -0.04019591, -1.08064626, -0.73818385, -0.54321985,
       -0.10194856, -0.59274301, -0.42230154, -2.17255921, -3.48756294])